#!/bin/bash
#it worked for you, you use and like it = donate any amount you wish
#BTC: 1HRjjHByNL2enV1eRR1RkN698tucecL6FA
#ETH: 0x4e5e7b86baf1f8d6dfb8a242c85201c47fa86c74
#ZEC: t1aKAm7qXi6fbGvAhbLioZm3Q8obb4e3BRo
echo "apps:">cfg/$1.yaml
echo "  - script : sh">>cfg/$1.yaml
echo "    name : '$1'">>cfg/$1.yaml
echo "    args : pair.sh $1">>cfg/$1.yaml
pm2 save
pm2 start cfg/$1.yaml
pm2 logs $1
